version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./conf/nginx/Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - "./data-www:/data/www"
      - /etc/localtime:/etc/localtime:ro
      - ./logs/nginx:/var/log/nginx:rw
    restart: always
    command: nginx
    depends_on:
        - php5-fpm
        - mariadb
        - redis
        
  php5-fpm:
    image: nanoninja/php-fpm:5.6.40
    container_name: php5-fpm
    restart: always
    volumes:
      - "./conf/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./data-www:/data/www"
    
  mariadb:
    image: mariadb:10.4
    restart: always
    container_name: mariaDB
    environment:
      MYSQL_ROOT_PASSWORD: yourpass
    ports:
      - "3306:3306"
    expose:
       - "3306"
    volumes:
      - ./data-mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      
  redis:
    image: redis
    ports:
      - "6379:6379"
